"""
Django settings for credit project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path

from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$-+zrwmz0-ymk!2a4eyt!3v+x54lz313g5z_z+gc!^o*277@91'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
 
 
]

ROOT_URLCONF = 'credit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'credit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'credit',       # your database name
        'USER': 'postgres',         # your postgres username
        'PASSWORD': 'sumanth2119',# your postgres password
        'HOST': 'localhost',
        'PORT': '5432',             # default for PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


TWILIO_ACCOUNT_SID = "AC903ca340f30b785d2a5857ff8a4753ab"
TWILIO_AUTH_TOKEN = "ff47f28372b0faf1c135e5e87ab79d6a"
TWILIO_FROM_PHONE = "+13159083763"  



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = 'en'
USE_I18N = True

LANGUAGES = [
    ('as', _('Assamese')),
    ('bn', _('Bengali')),
    ('brx', _('Bodo')),
    ('doi', _('Dogri')),
    ('en', _('English')),
    ('gu', _('Gujarati')),
    ('hi', _('Hindi')),
    ('kn', _('Kannada')),
    ('ks', _('Kashmiri')),
    ('kok', _('Konkani')),
    ('mai', _('Maithili')),
    ('ml', _('Malayalam')),
    ('mni', _('Manipuri')),
    ('mr', _('Marathi')),
    ('ne', _('Nepali')),
    ('or', _('Odia')),
    ('pa', _('Punjabi')),
    ('sa', _('Sanskrit')),
    ('sat', _('Santali')),
    ('sd', _('Sindhi')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('ur', _('Urdu')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]




TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
