# Generated by Django 5.2.8 on 2025-11-28 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('ELECTRICITY', 'Electricity Bill'), ('MOBILE', 'Mobile Bill'), ('WATER', 'Water Bill'), ('GAS', 'Gas Bill')], max_length=20)),
                ('document_number', models.CharField(help_text='Aadhaar number / PAN number / consumer number / phone number etc.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Scanned copy or photo of the document', null=True, upload_to='beneficiary_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.beneficiary')),
            ],
            options={
                'unique_together': {('beneficiary', 'doc_type')},
            },
        ),
    ]
