# Generated by custom change on 2025-11-30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_beneficiarydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case1Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payments_regularity', models.BooleanField(blank=True, null=True, help_text='Are payments regular? (Yes/No)')),
                ('average_mobile_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('working_days_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('digital_payment_frequency', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('average_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transactions_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case1_details', to='api.beneficiary')),
            ],
        ),
    ]
