# Generated by Django 5.2.8 on 2025-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_beneficiarydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
