# Generated by Django 5.2.8 on 2025-11-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_case2details'),
        ('api', '0008_beneficiary_aadhaar_verified_and_more'),
    ]

    operations = [
    ]
