# Generated by assistant on 2025-11-30
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_loanhistory_fk_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case3Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payments_regularity', models.BooleanField(blank=True, null=True, help_text='Are payments regular? (Yes/No)')),
                ('average_mobile_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('working_days_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('digital_payment_frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('average_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transactions_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_6_months_avg_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_active_loans', models.PositiveIntegerField(blank=True, null=True)),
                ('total_properties_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wealth_index', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('any_business', models.BooleanField(blank=True, null=True)),
                ('insurance_coverage', models.BooleanField(blank=True, null=True)),
                ('luxury_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('loan_history_cibil', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=False, null=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case3_details', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Case3Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.PositiveIntegerField(default=1, help_text='1 for loan1, 2 for loan2, etc.')),
                ('loan_type', models.CharField(blank=True, max_length=150, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_sanction_date', models.DateField(blank=True, null=True)),
                ('tenure_months', models.PositiveIntegerField(blank=True, null=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_emi_date', models.DateField(blank=True, null=True)),
                ('outstanding_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('loan_history_cibil', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=False, null=True)),
                ('case3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.case3details')),
            ],
            options={
                'ordering': ['loan_number'],
            },
        ),
    ]
