# Generated by Django 5.2.8 on 2025-11-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_case3details_created_at_and_more'),
        ('api', '0012_create_case4details'),
    ]

    operations = [
    ]
