# Generated by Django 5.2.8 on 2025-12-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_beneficiary_updated_at_alter_case4details_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='case_type',
            field=models.CharField(blank=True, help_text='One of CASE1/CASE2/CASE3/CASE4', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='loans_dues_change_reason',
            field=models.TextField(blank=True, help_text='Reason for changing number of loans or EMI due delays after first submission', null=True),
        ),
    ]
