# Generated by Django 5.2.8 on 2025-12-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_beneficiary_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='cibil_score',
            field=models.PositiveIntegerField(blank=True, help_text='Reported CIBIL score', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='credit_card_available',
            field=models.BooleanField(blank=True, help_text='Has credit card?', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='emi_due_delays',
            field=models.PositiveIntegerField(blank=True, help_text='No. of delayed EMIs', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='number_of_loans',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of loans', null=True),
        ),
    ]
