# Generated by Django 5.2.8 on 2025-12-04 02:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_beneficiary_cibil_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, choices=[('CASE1', 'Case 1'), ('CASE2', 'Case 2'), ('CASE3', 'Case 3'), ('CASE4', 'Case 4')], max_length=10, null=True)),
                ('electricity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payments_regularity', models.BooleanField(blank=True, help_text='Are payments regular? (Yes/No)', null=True)),
                ('average_mobile_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('working_days_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('digital_payment_frequency', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('average_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transactions_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_6_months_avg_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_active_loans', models.PositiveIntegerField(blank=True, null=True)),
                ('total_properties_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wealth_index', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('any_business', models.BooleanField(blank=True, null=True)),
                ('insurance_coverage', models.BooleanField(blank=True, null=True)),
                ('luxury_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('loan_history_cibil', models.TextField(blank=True, null=True)),
                ('reasons_for_delay', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_details', to='api.beneficiary')),
            ],
        ),
    ]
