# Generated by Django 5.2.8 on 2025-12-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_casedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case2details',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='case2loan',
            name='case2',
        ),
        migrations.RemoveField(
            model_name='case3details',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='case3loan',
            name='case3',
        ),
        migrations.RemoveField(
            model_name='case4details',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='case4loan',
            name='case4',
        ),
        migrations.AddField(
            model_name='casedetails',
            name='number_of_due_delays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='total_emi_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='Case1Details',
        ),
        migrations.DeleteModel(
            name='Case2Details',
        ),
        migrations.DeleteModel(
            name='Case2Loan',
        ),
        migrations.DeleteModel(
            name='Case3Details',
        ),
        migrations.DeleteModel(
            name='Case3Loan',
        ),
        migrations.DeleteModel(
            name='Case4Details',
        ),
        migrations.DeleteModel(
            name='Case4Loan',
        ),
    ]
