# Generated by Django 5.2.8 on 2025-12-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_case2details_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
